language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  
# Setup gui
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .[dev]
  - python setup.py install
# command to run tests
script:
  - python setup.py test
cache:
    directories:
        # Cache for pip, mostly to speed up matplotlib install
        - $HOME/.cache/pip
